version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: ./docker/web/dockerfile
    ports:
      - 8888:8888
  api:
    build: 
      context: .
      dockerfile: ./docker/api/dockerfile
    ports:
      - 3000:3000